// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: proto_name_lower.proto

/*
Package pb is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package pb

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/descriptor"
	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = descriptor.ForMessage
var _ = metadata.Join

func request_ProtoNameTitle_HelloProtoNameTitle_0(ctx context.Context, marshaler runtime.Marshaler, client ProtoNameTitleClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq HelloProtoNameTitleRequest
	var metadata runtime.ServerMetadata

	msg, err := client.HelloProtoNameTitle(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_ProtoNameTitle_HelloProtoNameTitle_0(ctx context.Context, marshaler runtime.Marshaler, server ProtoNameTitleServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq HelloProtoNameTitleRequest
	var metadata runtime.ServerMetadata

	msg, err := server.HelloProtoNameTitle(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterProtoNameTitleHandlerServer registers the http handlers for service ProtoNameTitle to "mux".
// UnaryRPC     :call ProtoNameTitleServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterProtoNameTitleHandlerFromEndpoint instead.
func RegisterProtoNameTitleHandlerServer(ctx context.Context, mux *runtime.ServeMux, server ProtoNameTitleServer) error {

	mux.Handle("GET", pattern_ProtoNameTitle_HelloProtoNameTitle_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_ProtoNameTitle_HelloProtoNameTitle_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_ProtoNameTitle_HelloProtoNameTitle_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterProtoNameTitleHandlerFromEndpoint is same as RegisterProtoNameTitleHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterProtoNameTitleHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterProtoNameTitleHandler(ctx, mux, conn)
}

// RegisterProtoNameTitleHandler registers the http handlers for service ProtoNameTitle to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterProtoNameTitleHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterProtoNameTitleHandlerClient(ctx, mux, NewProtoNameTitleClient(conn))
}

// RegisterProtoNameTitleHandlerClient registers the http handlers for service ProtoNameTitle
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "ProtoNameTitleClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "ProtoNameTitleClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "ProtoNameTitleClient" to call the correct interceptors.
func RegisterProtoNameTitleHandlerClient(ctx context.Context, mux *runtime.ServeMux, client ProtoNameTitleClient) error {

	mux.Handle("GET", pattern_ProtoNameTitle_HelloProtoNameTitle_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_ProtoNameTitle_HelloProtoNameTitle_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_ProtoNameTitle_HelloProtoNameTitle_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_ProtoNameTitle_HelloProtoNameTitle_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"hello", "proto-name-dash"}, "", runtime.AssumeColonVerbOpt(true)))
)

var (
	forward_ProtoNameTitle_HelloProtoNameTitle_0 = runtime.ForwardResponseMessage
)
