// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto_name_lower_message.proto

package pb

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/mwitkow/go-proto-validators"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HelloProtoNameTitleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloProtoNameTitleRequest) Reset()         { *m = HelloProtoNameTitleRequest{} }
func (m *HelloProtoNameTitleRequest) String() string { return proto.CompactTextString(m) }
func (*HelloProtoNameTitleRequest) ProtoMessage()    {}
func (*HelloProtoNameTitleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dfea2bc3905003d, []int{0}
}
func (m *HelloProtoNameTitleRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HelloProtoNameTitleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HelloProtoNameTitleRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HelloProtoNameTitleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloProtoNameTitleRequest.Merge(m, src)
}
func (m *HelloProtoNameTitleRequest) XXX_Size() int {
	return m.Size()
}
func (m *HelloProtoNameTitleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloProtoNameTitleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloProtoNameTitleRequest proto.InternalMessageInfo

type HelloProtoNameTitleResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloProtoNameTitleResponse) Reset()         { *m = HelloProtoNameTitleResponse{} }
func (m *HelloProtoNameTitleResponse) String() string { return proto.CompactTextString(m) }
func (*HelloProtoNameTitleResponse) ProtoMessage()    {}
func (*HelloProtoNameTitleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9dfea2bc3905003d, []int{1}
}
func (m *HelloProtoNameTitleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HelloProtoNameTitleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HelloProtoNameTitleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HelloProtoNameTitleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloProtoNameTitleResponse.Merge(m, src)
}
func (m *HelloProtoNameTitleResponse) XXX_Size() int {
	return m.Size()
}
func (m *HelloProtoNameTitleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloProtoNameTitleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloProtoNameTitleResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*HelloProtoNameTitleRequest)(nil), "pb.HelloProtoNameTitleRequest")
	proto.RegisterType((*HelloProtoNameTitleResponse)(nil), "pb.HelloProtoNameTitleResponse")
}

func init() { proto.RegisterFile("proto_name_lower_message.proto", fileDescriptor_9dfea2bc3905003d) }

var fileDescriptor_9dfea2bc3905003d = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8c, 0x31, 0x4e, 0xc4, 0x30,
	0x10, 0x45, 0x15, 0x0a, 0x8a, 0x54, 0x88, 0x32, 0x2c, 0x2e, 0xb6, 0xc6, 0xeb, 0x02, 0x89, 0x03,
	0x50, 0x51, 0x21, 0x84, 0xe8, 0xa3, 0xc9, 0x32, 0x0c, 0x16, 0xb6, 0xbf, 0x89, 0x1d, 0x72, 0x25,
	0x8e, 0x42, 0xc9, 0x11, 0x50, 0x4e, 0x82, 0x98, 0x45, 0x88, 0x22, 0xd5, 0xfc, 0x3f, 0xef, 0xcd,
	0xb4, 0x26, 0x8f, 0xa8, 0xe8, 0x13, 0x45, 0xee, 0x03, 0x66, 0x1e, 0xfb, 0xc8, 0xa5, 0x90, 0xf0,
	0x4e, 0xc1, 0xe9, 0x51, 0x1e, 0xba, 0x8d, 0x00, 0x12, 0xd8, 0x51, 0xf6, 0x8e, 0x52, 0x42, 0xa5,
	0xea, 0x91, 0xca, 0xc1, 0xe8, 0x2e, 0x74, 0xec, 0xad, 0x70, 0xb2, 0x65, 0x26, 0x11, 0x1e, 0x1d,
	0xb2, 0x1a, 0x2b, 0xb6, 0x15, 0x5f, 0x9f, 0xa7, 0x61, 0xb7, 0x47, 0x74, 0x02, 0x81, 0xd3, 0xf5,
	0x30, 0x3d, 0x69, 0xd3, 0xa2, 0xe9, 0x57, 0xbf, 0xfa, 0xa7, 0xc7, 0xd9, 0xd7, 0x17, 0xcc, 0x4e,
	0x60, 0x15, 0xda, 0x37, 0x0a, 0xfe, 0x91, 0x2a, 0xc6, 0xe2, 0xfe, 0xe2, 0xe1, 0x6e, 0xbb, 0x69,
	0xbb, 0x1b, 0x0e, 0x01, 0x77, 0x3f, 0xed, 0x96, 0x22, 0x3f, 0xf8, 0x1a, 0xf8, 0x9e, 0x5f, 0x27,
	0x2e, 0x75, 0x7b, 0xde, 0x9e, 0xad, 0xd2, 0x92, 0x91, 0x0a, 0x5f, 0x9f, 0xbc, 0x2f, 0xa6, 0xf9,
	0x58, 0x4c, 0xf3, 0xb9, 0x98, 0xe6, 0x6b, 0x31, 0xcd, 0x70, 0xac, 0x5f, 0x2f, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x52, 0xc7, 0x13, 0xda, 0x2e, 0x01, 0x00, 0x00,
}

func (this *HelloProtoNameTitleRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HelloProtoNameTitleRequest)
	if !ok {
		that2, ok := that.(HelloProtoNameTitleRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *HelloProtoNameTitleResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*HelloProtoNameTitleResponse)
	if !ok {
		that2, ok := that.(HelloProtoNameTitleResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (m *HelloProtoNameTitleRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HelloProtoNameTitleRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HelloProtoNameTitleRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *HelloProtoNameTitleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HelloProtoNameTitleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HelloProtoNameTitleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func encodeVarintProtoNameLowerMessage(dAtA []byte, offset int, v uint64) int {
	offset -= sovProtoNameLowerMessage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HelloProtoNameTitleRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *HelloProtoNameTitleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovProtoNameLowerMessage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProtoNameLowerMessage(x uint64) (n int) {
	return sovProtoNameLowerMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HelloProtoNameTitleRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProtoNameLowerMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HelloProtoNameTitleRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HelloProtoNameTitleRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipProtoNameLowerMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProtoNameLowerMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HelloProtoNameTitleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProtoNameLowerMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HelloProtoNameTitleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HelloProtoNameTitleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipProtoNameLowerMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProtoNameLowerMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProtoNameLowerMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProtoNameLowerMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProtoNameLowerMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProtoNameLowerMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProtoNameLowerMessage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProtoNameLowerMessage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProtoNameLowerMessage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProtoNameLowerMessage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProtoNameLowerMessage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProtoNameLowerMessage = fmt.Errorf("proto: unexpected end of group")
)
